# Generated by Django 3.1.7 on 2021-03-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('setcens', models.FloatField(blank=True, default=None, null=True)),
                ('areap', models.FloatField(blank=True, default=None, null=True)),
                ('cod_dist', models.IntegerField(blank=True, default=None, null=True)),
                ('district', models.TextField(blank=True, default=None, null=True)),
                ('cod_sub_prefecture', models.TextField(blank=True, default=None, null=True)),
                ('sub_prefecture', models.TextField(blank=True, default=None, null=True)),
                ('region_5', models.TextField(blank=True, choices=[('Leste', 'East'), ('Oeste', 'West'), ('Sul', 'South'), ('Norte', 'North')], default=None, null=True)),
                ('region_8', models.TextField(blank=True, default=None, null=True)),
                ('name', models.TextField(blank=True, default=None, null=True)),
                ('registration_code', models.TextField(unique=True)),
                ('address_street', models.TextField(blank=True, default=None, null=True)),
                ('address_number', models.TextField(blank=True, default=None, null=True)),
                ('address_city', models.TextField(blank=True, default=None, null=True)),
                ('reference', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
